### ISSUE TITLE
Question about failed to create a pool

### ISSUE THREAD

**Issue by yzx2337** [baotonglu/dash#10]
`static const char* layout_name = "hashtable";`
`pm_pool_ = pmemobj_create_addr(pool_name, layout_name, pool_size,CREATE_MODE_RW, (void*)pool_addr);`

I tried to run the "test_pmem" and "example". However,both of them got an error called "failed to create a pool;". I think the reason is that the layout_name might be incomplete.  Should I finish the layout_name by myself?

**Comment by baotonglu** [comment]
Hi,

I don't have this problem when I run it on my machine. Probably you could consider creating a small memory pool.

Baotong
