### ISSUE TITLE
What is the specific process of rehashing?

### ISSUE THREAD

**Issue by sunce4t** [baotonglu/dash#12]
Hi, I have a small problem after reading Dash, that is, how do you deal with the insertion request in the process of rehashing, do you lock the entire segment? I did not find a specific description in the paper.
Thanks!

**Comment by baotonglu** [comment]
Yes, we lock all buckets in the rehashing segments.

**Comment by sunce4t** [comment]
> Yes, we lock all buckets in the rehashing segments.

Thanks for your reply!
