### ISSUE TITLE
fatal error: garbage_list.h: No such file or directory

### ISSUE THREAD

**Issue by lawben** [baotonglu/dash#3]
In `allocator.h` there is an `#include <garbage_list.h>`. However, there is no `garbage_list.h` in the repository, so it does not build. Is this some external dependency or is it simply missing in the repository?

**Comment by baotonglu** [comment]
Hi, 

"garbage_list.h" is the external dependency which is avaiable at  "https://github.com/XiangpengHao/VeryPM". Our cmake file has linked to this repository. I think you should have no problems if you follow our build steps. 

Baotong

**Comment by lawben** [comment]
Ah, thanks. Your cmake works, the problem is in my setup. I included dash via `add_subdirectory` and that does not propagate the include directories from sub-cmakes. I needed to explicitly call `include_directories` in my cmake root file.
