### ISSUE TITLE
Question about dummy

### ISSUE THREAD

**Issue by shiniaas** [baotonglu/dash#4]
In the definition of Table, a member `char dummy[48];` exists(ex_finger.h:867), and I wonder the effect of it.
Is it for the alignment of something else?
Thanks.

**Comment by baotonglu** [comment]
It is for cache-line alignment (64byte).  PMDK allocation is always cache-line aligned but it internally puts some metadata in the first 16 bytes. So we add 48-byte dummy data for alignment.
