### ISSUE TITLE
MAP_FIXED_NOREPLACE requires glibc 2.29 or greater

### ISSUE THREAD

**Issue by nisargshah95** [baotonglu/dash#6]
It seems that the new flag requires glibc 2.29 or newer. On my Ubuntu 18.04 system I upgraded linux kernel to 5.4 but the custom PMDK still wouldn't compile because glibc was 2.27. Once I upgraded my system to 20.04 (which also installed glibc 2.31), I could build it successfully.
Might be helpful to add this to the README.

**Comment by baotonglu** [comment]
Thanks. I will update the README.
