### ISSUE TITLE
the origin of the name

### ISSUE THREAD

**Issue by romange** [baotonglu/dash#9]
Hi, Dash is a great algorithm and a great piece of engineering. 

I think it has applications beyond the persistent memory domain. 
Few questions.
1) What's the origin of the name "dash" ? What does it mean?
2) Seems that many design choices are applicable for a main memory hash table as well. Did you try comparing dash table to other state-of-the-art implementations?

**Comment by wangtzh** [comment]
Hi Roman - Thanks for the comments! It's "**d**ynamic **a**nd **s**calable **h**ashing."

Indeed, the design choices can be applicable to DRAM main memory as well. We have an early DRAM port as part of ERMIA (https://github.com/sfu-dis/ermia/tree/hash) but haven't compared it with other DRAM hash tables (we are in fact comparing PM range indexes vs. main memory indexes, and may extend to include hash tables later).

**Comment by romange** [comment]
Got ya. will take a look!
